"""Generated closed private catalog; checked against HTTP sources by tests."""

CALLS: tuple[tuple[str, str, str | None, str, str, str | None, str], ...] = (
    ("GET", "/admin/v1/status", None, "m50", "read", None, "m44"),
    ("GET", "/admin/v1/config", None, "m66", "read", None, "m44"),
    ("GET", "/admin/v1/rules", None, "m69", "read", None, "m44"),
    ("GET", "/admin/v1/rules/{rule_id}", None, "m70", "read", "rule_id", "m44"),
    ("GET", "/admin/v1/exceptions", None, "m73", "read", None, "m44"),
    ("GET", "/admin/v1/exceptions/{exception_id}", None, "m74", "read", "exception_id", "m44"),
    ("GET", "/admin/v1/transformers", None, "m77", "read", None, "m44"),
    ("GET", "/admin/v1/protected", None, "m79", "read", None, "m44"),
    ("POST", "/admin/v1/config:validate", "m89", "m91", "check", None, "m44"),
    ("POST", "/admin/v1/config:adopt", "m92", "m93", "confirm", None, "m44"),
    ("POST", "/admin/v1/rules:reorder", "m95", "m93", "move", None, "m44"),
    ("POST", "/admin/v1/rules", "m98", "m93", "create", None, "m44"),
    ("PUT", "/admin/v1/rules/{rule_id}", "m99", "m93", "replace", "rule_id", "m44"),
    ("DELETE", "/admin/v1/rules/{rule_id}", "m100", "m93", "delete", "rule_id", "m44"),
    ("POST", "/admin/v1/exceptions", "m102", "m93", "create", None, "m44"),
    ("PUT", "/admin/v1/exceptions/{exception_id}", "m102", "m93", "replace", "exception_id", "m44"),
    (
        "DELETE",
        "/admin/v1/exceptions/{exception_id}",
        "m100",
        "m93",
        "delete",
        "exception_id",
        "m44",
    ),
    ("PUT", "/admin/v1/database", "m103", "m93", "replace", None, "m44"),
    ("PUT", "/admin/v1/sql", "m104", "m93", "append", None, "m44"),
    ("GET", "/admin/v2/status", None, "m125", "read", None, "m120"),
    ("GET", "/admin/v2/datasources", None, "m133", "read", None, "m120"),
    ("GET", "/admin/v2/datasources/{datasource_id}", None, "m140", "read", "datasource_id", "m120"),
    (
        "GET",
        "/admin/v2/datasources/{datasource_id}/policy",
        None,
        "m146",
        "read",
        "datasource_id",
        "m120",
    ),
    ("POST", "/admin/v2/datasources", "m200", "m201", "register", None, "m182"),
    ("POST", "/admin/v2/datasources:test", "m202", "m203", "probe", None, "m182"),
    (
        "POST",
        "/admin/v2/datasources/{datasource_id}:test",
        "m106",
        "m203",
        "probe",
        "datasource_id",
        "m182",
    ),
    (
        "POST",
        "/admin/v2/datasources/{datasource_id}:rotate-credential",
        "m205",
        "m201",
        "renew",
        "datasource_id",
        "m182",
    ),
    (
        "POST",
        "/admin/v2/datasources/{datasource_id}:enable",
        "m206",
        "m201",
        "resume",
        "datasource_id",
        "m182",
    ),
    (
        "POST",
        "/admin/v2/datasources/{datasource_id}:disable",
        "m206",
        "m201",
        "pause",
        "datasource_id",
        "m182",
    ),
    (
        "PUT",
        "/admin/v2/datasources/{datasource_id}",
        "m207",
        "m201",
        "revise",
        "datasource_id",
        "m182",
    ),
    (
        "DELETE",
        "/admin/v2/datasources/{datasource_id}",
        "m208",
        "m209",
        "retire",
        "datasource_id",
        "m182",
    ),
    (
        "PUT",
        "/admin/v2/datasources/{datasource_id}/policy",
        "m210",
        "m201",
        "amend",
        "datasource_id",
        "m182",
    ),
)
MODEL_SHA256 = "378b20ccdd8f7fb18f5047aee9976fe08761aeb97f6fafad6c1ab364009f8c34"
